title: Your awesome title
author: GitHub User
email: sexymahyuls@6emahyuls.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is shitm but it's good shit coz it's a learning experience. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
